apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: banker
  name: banker-deployment
  labels:
    app: banker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: banker
  template:
    metadata:
      labels:
        app: banker
    spec:
      containers:
      - name: banker
        image: "ghcr.io/robaertschi/banker/banker:latest"
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
          - name: DB_HOST
            value: mongodb-service.banker.svc.cluster.local
